config/routes.rb
Rails.application.routes.draw do
  resources :tools

end

app/models/tool.rb
class Tool < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  def index
    @tools = Tool.all
  end

  def show
    @tool = Tool.find(params[:id])
  end

  def new
    @tool = Tool.new
  end

  def edit
    @tool = Tool.find(params[:id])
  end

  def update
    @tool = Tool.find(params[:id])
    if @tool.update(tool_params)
      redirect_to tool_path(@tool)
    else
      render :edit
    end
  end

  def create
    @tool = Tool.new(tool_params)
    if @tool.save
      redirect_to tool_path(@tool)
    else
      render :new
    end
  end

  def destroy
    @tool = Tool.find(params[:id])
    @tool.destroy
    redirect_to tools_path
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :quantity, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolChest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tools/edit.html.erb
<%= form_for(@tool) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.label :quantity %>
  <%= f.text_field :quantity %>

  <%= f.submit %>
<% end %>

app/views/tools/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Tool Info</h1>
      <% @tools.each do |tool| %>
        <b>Tool</b>: <%= link_to tool.name, tool_path(tool) %><br>
        <b>Quantity</b>: <%= tool.quantity %><br>
        <b>Price</b>: $<%= tool.price %><br><br><br>
      <% end %>
    </div>
  </div>
</div>

<%= link_to "Add a New Tool", new_tool_path %>

app/views/tools/new.html.erb
<%= form_for(@tool) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  
  <%= f.submit %>
<% end %>

app/views/tools/show.html.erb
<div class="container" id="tool_info">
  <div class="row">
    <div class="col-sm-12">
      <h2><%= @tool.name %></h2>
      <h4><u>Quantity</u>: <%= @tool.quantity %></h4>
      <h4><u>Price</u>: <%= @tool.price %></h4>
    </div>
  </div>
</div>

<%= link_to "Edit Tool", edit_tool_path %>
<br>
<%= link_to "Delete Tool", tool_path(@tool), method: :delete %>